
package vista.panels;

import controlador.Coordinador;
import java.util.HashMap;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.InfoTabla.DepartamentoIT;
import modelo.InfoTabla.EmpleadoIT;
import modelo.Textos;
import modelo.logica.Validacion;
import modelo.vo.DepartamentoVo;
import modelo.vo.EmpleadoVo;
import modelo.FechaYHora;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.OperacionesBasicasPorDefinir;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesBotones_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesComboBox_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesListas_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesTxt_;

/**
 *
 * @author Particular
 */
public class DialogoEmpleadoModificar extends javax.swing.JDialog {
    Coordinador coordinador;
    
    UtilidadesTxt_ _txtNombre;
    UtilidadesTxt_ _txtBusqueda;
    UtilidadesComboBox_ _comboDepartamentos;
    UtilidadesListas_ _listaEmpleados;
    boolean cargarEmpleadosDadosDeBaja;
    
    boolean empleadoAdelantado= false;
    
    /**
     * Creates new form DialogoAgregarEmpleado
     */
    public DialogoEmpleadoModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        etiquetaDepartamento = new javax.swing.JLabel();
        comboDepartamento = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList<>();
        btnDarDeBajaAlta = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkMostrarEmpleadosDadosDeBaja = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(98, 15, 89));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_titulo_modificar empleado.png"))); // NOI18N

        etiquetaNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaNombre.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setMaximumSize(new java.awt.Dimension(395, 2147483647));
        txtNombre.setMinimumSize(new java.awt.Dimension(395, 35));

        etiquetaDepartamento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaDepartamento.setText("Departamento");

        comboDepartamento.setEditable(true);
        comboDepartamento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comboDepartamento.setMinimumSize(new java.awt.Dimension(195, 32));

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/iconos_palomita.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/iconos_tache.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        listaEmpleados.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        listaEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEmpleados);

        btnDarDeBajaAlta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnDarDeBajaAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/iconos_tache.png"))); // NOI18N
        btnDarDeBajaAlta.setText("Dar de baja");
        btnDarDeBajaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeBajaAltaActionPerformed(evt);
            }
        });

        txtBusqueda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/iconos_buscar.png"))); // NOI18N

        checkMostrarEmpleadosDadosDeBaja.setText("Mostrar empleados dados de baja");
        checkMostrarEmpleadosDadosDeBaja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkMostrarEmpleadosDadosDeBajaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDarDeBajaAlta))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDepartamento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkMostrarEmpleadosDadosDeBaja)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkMostrarEmpleadosDadosDeBaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaNombre)
                            .addComponent(btnDarDeBajaAlta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCancelar)
                                .addComponent(btnGuardar))
                            .addComponent(comboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void configurar(){
        configurar("");
    }
    
    /**
     * Cofiguraciones para el dialogo.  
     * @param empleadoAdelantado El nombre del empleado para rellenar. 
     */
    public void configurar(String empleadoAdelantado){
     /*
        =======================================================================
            INICIO CONFIGURACIONES DIALOGO
        ///////////////////////////////////////////////////////////////////////

        Los dialogos nos los estoy configurando de manera complicada. Solo lo
        básico para que funcionen en modal.
        
        */ 
        setModal(false);
        setResizable(false);
        setTitle("Agregar nuevo empleado");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN SETEO DE UTILIDADES
        ========================================================================
        */
        
       
        
        
        /*
        =======================================================================
            INICIO SETEO NOMBRES DE ETIQUETA
        ///////////////////////////////////////////////////////////////////////
        */
        EmpleadoIT eit = new EmpleadoIT();
        DepartamentoIT dit = new DepartamentoIT();
        
        etiquetaDepartamento.setText(dit.getDepartamentoPDC().getNombreParaMostrar());
        etiquetaNombre.setText(eit.getNombrePDC().getNombreParaMostrar());
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN SETEO NOMBRES DE ETIQUETA
        ========================================================================
        */
        
        /*
        =======================================================================
            INICIO SETEO UTILIDADES
        ///////////////////////////////////////////////////////////////////////
        */
        //INICIAMOS LAS UTILIDADES.
       
        _txtNombre = new UtilidadesTxt_(coordinador);
        _txtBusqueda = new UtilidadesTxt_(coordinador);
        _comboDepartamentos = new UtilidadesComboBox_(coordinador);
        _listaEmpleados = new UtilidadesListas_(coordinador);
        
        
        //SETEAMOS LOS COMPONENTES DENTRO DE LA UTILIDAD.
        _txtNombre.setComponente(txtNombre);
        _txtBusqueda.setComponente(txtBusqueda);
        _comboDepartamentos.setComponente(comboDepartamento);
        _listaEmpleados.setComponente(listaEmpleados);
       
        //ASIGNAMOS EL TAMAÑO DE CAMPO
        
        _txtBusqueda.setTamanoDeCampo(300);
        _txtNombre.setTamanoDeCampo(eit.getNombrePDC().getLongitudDeCaracteres());
        _comboDepartamentos.setTamanoDeCampo(dit.getDepartamentoPDC().getLongitudDeCaracteres());

        //CAMPOS QUE REQUIEREN TEXTO EN MAYUSCULAS.
        _txtNombre.setPermitirSoloMayusculas();
        _comboDepartamentos.setPermitirSoloMayusculas();
        _txtBusqueda.setPermitirSoloMayusculas();
        
        //QUITAMOS LOS ESPACIOS SOBRANTES DESPUES DE DEJAR EL CAMPO.
        _txtNombre.setEspaciosEnBlanco();
        _comboDepartamentos.setEspaciosEnBlanco();
        _txtBusqueda.setEspaciosEnBlanco();
        
        //ACCIONES ESPECELIALES.
        _comboDepartamentos.setFocusAction(()->guardarDepartamento(), false);
        _txtBusqueda.setKeyRelease(()->busqueda(), OperacionesBasicasPorDefinir.TECLA_CUALQUIERA_EXCEPTO_ENTER);
      
        
        //ACCIONES DE BOTONES
        UtilidadesBotones_.setEnterYEspacio(btnCancelar);
        UtilidadesBotones_.setEnterYEspacio(btnGuardar);
        _listaEmpleados.setValueChange(()->this.cargarEmpleado());
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN SETEO DE UTILIDADES
        ========================================================================
        */
        /*
        =======================================================================
            INICIO CARGA DE ELEMENTOS 
        ///////////////////////////////////////////////////////////////////////
        */
        _txtNombre.setText(empleadoAdelantado);
        this.cargarComboDepartamentos();
        this.cargarListaEmpleados();
            
        if (!empleadoAdelantado.equals("")) {
            this.empleadoAdelantado = true;
        }
            
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN CARGA DE ELEMENTOS 
        ========================================================================
        */    
    
    }
    
    public void busqueda(){
        if (!_txtBusqueda.isEmpty()) {
            cargarListaEmpleadosBusqueda(_txtBusqueda.getText());
        }else{
            _listaEmpleados.limpiar();
            limpiar();
            cargarListaEmpleados();
        }
    
    }
    
    private void cargarListaEmpleadosBusqueda(String busqueda){
        _listaEmpleados.limpiar();
        List<EmpleadoVo> listVo = this.coordinador.empleadoConsultarBusquedaConBajas(busqueda);
        cargarListaEmpleados(listVo);
    }
    
    
    
    public void cargarEmpleado(){
        Object a = _listaEmpleados.getSelectValueId();
        if (!a.equals(-1)) {
            EmpleadoVo vo = (EmpleadoVo) a;
            if (vo.getBajaEmpleado()==1) {
                btnDarDeBajaAlta.setText("Dar de alta");
                btnDarDeBajaAlta.setIcon(new ImageIcon(getClass().getResource("/Vista/imagenes/iconos_palomita.png")));
            }else{
                btnDarDeBajaAlta.setText("Dar de baja");
                btnDarDeBajaAlta.setIcon(new ImageIcon(getClass().getResource("/Vista/imagenes/iconos_tache.png")));
            
            }
            _txtNombre.setText(vo.getNombre());
            _comboDepartamentos.setSelectedItem(vo.getIdDepartamento());
            this.repaint();
        }
    };
    
    public void cargarListaEmpleados(){
        List<EmpleadoVo> listVo = this.getCoordinador().empleadoConsultarTodoConBajas();
        cargarListaEmpleados(listVo);
    }
    
    public void cargarListaEmpleados(List<EmpleadoVo> listVo){
        HashMap<String, Object> datos = new HashMap<>();
        for (EmpleadoVo vo : listVo) {
            
            String leyendaBaja = "||BAJA||";
            String nombre = "";
            String departamento = "";
            
            
            if (vo.getBajaEmpleado()==(byte)1) {
                if (cargarEmpleadosDadosDeBaja) {
                    nombre = Textos.formatearEspacios(30, leyendaBaja+vo.getNombre(),"|");
                    departamento = Textos.formatearEspacios(15,  (String)vo.getIdDepartamento()," ");
                }
            }else{
                nombre = Textos.formatearEspacios(30, vo.getNombre(),"|");
                departamento = Textos.formatearEspacios(15,  (String)vo.getIdDepartamento()," ");
            }
                
            datos.put(nombre+departamento, vo);
        }
               
        
        _listaEmpleados.cargarLista(datos);
        
        
    }
    
    private boolean guardarDepartamento(){
        String elementoEscrito = this._comboDepartamentos.getText();
        if (this._comboDepartamentos.contieneElItemEscrito()) {
            this._comboDepartamentos.setSelectedItem(elementoEscrito);
            return true;
        }else{
            this._comboDepartamentos.setErrorQuitar();
            if (!elementoEscrito.equals("")) {
                if (this._comboDepartamentos.contieneElItemEscrito(elementoEscrito)) {
                    this._comboDepartamentos.setSelectedItem(elementoEscrito);
                }else{
                    int respuesta = JOptionPane.showConfirmDialog(this,
                            "¿Estas segúro que quieres guardar \n "
                           + " el nuevo departamento \" "+this._comboDepartamentos.getText()+"\"?", 
                            "Guardar nuevo departamento.", JOptionPane.YES_NO_OPTION);
                    if (respuesta==JOptionPane.YES_OPTION) {
                        DepartamentoVo vo = new DepartamentoVo();
                        vo.setDepartamento(this._comboDepartamentos.getText());
                        this.coordinador.departamentoGuardar(vo);
                    }else{
                        this._comboDepartamentos.setText("");
                    }
                }
            }
        }
        this.cargarComboDepartamentos();
        this._comboDepartamentos.setSelectedItem(elementoEscrito);
        return true;
        
    }
    
    public void cargarComboDepartamentos(){
        List<DepartamentoVo> listaDepartamentos = this.coordinador.departamentoConsultarTodo();
        HashMap<String, Object> datosDepartamentos = new HashMap<>();
        for (DepartamentoVo vo : listaDepartamentos) {
            datosDepartamentos.put(vo.getDepartamento(), vo.getId());
        }
        _comboDepartamentos.cargarCombo(datosDepartamentos);
    
    }
    
    public void limpiar(){
        _txtNombre.setText("");
        _comboDepartamentos.limpiar();
        
        _txtNombre.setErrorQuitar();
        _comboDepartamentos.setErrorQuitar();
    }
    
    public boolean cancelar(){
        this.dispose();
        boolean todoVacio = true;
        if (!_txtNombre.isEmpty() ||
            !_comboDepartamentos.isEmpty()) {
            todoVacio=false;
        }
        if (todoVacio) {
            limpiar();
            this.dispose();
            return true;
            
        } else {
            if (empleadoAdelantado && !_txtNombre.isEmpty()) {
                this.getCoordinador().entradaLoteDialogoSetearItemCombo(_txtNombre.getText());
            }
            this.limpiar();
            this.dispose();
            
        }
        return true;
    }
    

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        EmpleadoVo vo = new EmpleadoVo();
        EmpleadoVo v = (EmpleadoVo)_listaEmpleados.getSelectValueId();
        vo.setId(v.getId());
        vo.setNombre(_txtNombre.getText());
        vo.setIdDepartamento(_comboDepartamentos.getSelectedItem_idRetorno());
        
        List<Validacion> validaciones = this.getCoordinador().empleadoValidarCampos(vo);
        DepartamentoIT it = new DepartamentoIT();
        
        boolean todoValido = true;
        
        for (Validacion val : validaciones) {
            if (val.getNombreDeCampo().equals(it.getDepartamentoPDC().getNombre())) {
                if (!val.isValido()) {
                    _txtNombre.setError(val.getMensajeDeError());
                }else{
                    _txtNombre.setErrorQuitar();
                }
            }
            
            if (!val.isValido()) {
                String mensaje = val.getNombreDeCampo()+":"+val.getMensajeDeError();
                JOptionPane.showMessageDialog(this, mensaje);
                todoValido = false;
            }
        }
        
        if (todoValido) {
            //GUARDAMOS EL EMPLEADO.
            if (this.getCoordinador().empleadoModificar(vo)) {
                limpiar();
                cargarListaEmpleados();
                JOptionPane.showMessageDialog(this, "Se modifico correctamente el empleado.");
            }else{
                JOptionPane.showMessageDialog(this, 
                        "Algo sucedio y no se modifico el empleado.", 
                        "No se modifico el empleado.", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    
    private void btnDarDeBajaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeBajaAltaActionPerformed
        Object a = _listaEmpleados.getSelectValueId();
        if (!a.equals(-1)) {
            EmpleadoVo vo = (EmpleadoVo)a;
            vo.setFechaBaja(FechaYHora.Actual.getFecha_DateSQL());
            if (vo.getBajaEmpleado()==(byte)0) 
                vo.setBajaEmpleado((byte) 1);
            else
                vo.setBajaEmpleado((byte) 0);
            
            
            if(this.coordinador.empleadoDarDeBajaAlta(vo))
                cargarListaEmpleados();
            else
                JOptionPane.showMessageDialog(this, "No se pudo dar de baja al empleado.");
        }
        
    }//GEN-LAST:event_btnDarDeBajaAltaActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void checkMostrarEmpleadosDadosDeBajaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkMostrarEmpleadosDadosDeBajaItemStateChanged
        if (checkMostrarEmpleadosDadosDeBaja.isSelected()) {
            cargarEmpleadosDadosDeBaja = true;
//            JOptionPane.showMessageDialog(null, cargarEmpleadosDadosDeBaja+": cargarEmpleadosDadosDeBaja");
            cargarListaEmpleados();
        }else{
            cargarEmpleadosDadosDeBaja = false;
            cargarListaEmpleados();
        }
        
    }//GEN-LAST:event_checkMostrarEmpleadosDadosDeBajaItemStateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDarDeBajaAlta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox checkMostrarEmpleadosDadosDeBaja;
    private javax.swing.JComboBox<String> comboDepartamento;
    private javax.swing.JLabel etiquetaDepartamento;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaEmpleados;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
