/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panels;

import controlador.CoordinadorPaneles;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import modelo.InfoTabla.EntradaLoteIT;
import modelo.Textos;
import modelo.logica.ComparacionLotes;
import vista.UtilidadesIntefaz.ConfiguracionDePanel;
import vista.UtilidadesIntefaz.JPanelBase;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.ColoresYFuentes;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesJXViewImage_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesTxt_;

/**
 *
 * @author Particular
 */
public class PanelSalidaDeLoteCantidadADescontarDeLote extends JPanelBase {

    /**
     * Creates new form PanelSalidaDeLoteCantidadADescontarDeLote
     */
    public PanelSalidaDeLoteCantidadADescontarDeLote() {
        initComponents();
        configuracionesDialogo = new ConfiguracionDePanel();
        configuracionesDialogo.setModal(true);
        configuracionesDialogo.setResizable(true);
        configuracionesDialogo.setTitle(CoordinadorPaneles.PANEL_SALIDA_LOTE_SELECCION_DE_LOTES);
        configuracionesDialogo.setLocationRelativeTo(null);
        configuracionesDialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        etiquetaExistencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        etiquetaExistencia.setBackground(new java.awt.Color(51, 51, 51));
        etiquetaExistencia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaExistencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaExistencia.setText("Existencia");
        etiquetaExistencia.setOpaque(true);
        etiquetaExistencia.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lote");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(etiquetaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "no se ha definido la accion.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    @Override
    public void configurar() {
        panelContenedor.removeAll();
    }
    
    public void cargarLotes(List<ComparacionLotes>comparacionLotes){
        panelContenedor.setLayout(new FlowLayout(FlowLayout.LEADING));
        JPanel subPanel = new JPanel();
        subPanel.setLayout(new BoxLayout(subPanel, BoxLayout.Y_AXIS));
        for (ComparacionLotes cl : comparacionLotes) {
            ContenedorDeFila f = new ContenedorDeFila(cl);
            
            subPanel.add(f);
            subPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        }
        JScrollPane jScrollPane = new JScrollPane(subPanel);
        jScrollPane.setPreferredSize(new Dimension(panelContenedor.getSize()));
        panelContenedor.add(jScrollPane);
                
        panelContenedor.validate();
        this.validate();
        
    
    }
    
    class ContenedorDeFila extends JPanel{
        
        ComparacionLotes cl;
        JLabel etiquetaLote;
        JLabel etiquetaExistencia;
        JTextField recuadroEntrada;
        
        
        UtilidadesTxt_ _txtRecuadroEntrada;

        public ContenedorDeFila(ComparacionLotes cl) {
            this.cl = cl;
            generarFila();
        }

        private void generarFila() {
            setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
            etiquetaLote = new JLabel();
            etiquetaExistencia = new JLabel();
            recuadroEntrada = new JTextField();
            
            Dimension dimRec = new Dimension(80, 30);
            Dimension dimEti = new Dimension(100, 30);
            
            recuadroEntrada.setPreferredSize(dimRec);
            recuadroEntrada.setMinimumSize(dimRec);
            recuadroEntrada.setMaximumSize(dimRec);
            
            etiquetaExistencia.setPreferredSize(dimEti);
            etiquetaExistencia.setMinimumSize(dimEti);
            etiquetaExistencia.setMaximumSize(dimEti);
            
            etiquetaLote.setAlignmentX(Component.CENTER_ALIGNMENT);
            etiquetaExistencia.setAlignmentX(Component.CENTER_ALIGNMENT);
            recuadroEntrada.setAlignmentX(Component.CENTER_ALIGNMENT);
            
            etiquetaLote.setVerticalAlignment(SwingConstants.CENTER);
            etiquetaExistencia.setHorizontalAlignment(SwingConstants.CENTER);
            etiquetaExistencia.setVerticalAlignment(SwingConstants.CENTER);
            etiquetaLote.setHorizontalAlignment(SwingConstants.CENTER);
            

            etiquetaLote.setOpaque(true);
            etiquetaExistencia.setOpaque(true);
            etiquetaExistencia.setBackground(ColoresYFuentes.TEMA_FONDO_ETIQUETAS_OSCURO);
            
            etiquetaLote.setFont(ColoresYFuentes.FUENTE_ALINEADA);
            etiquetaExistencia.setFont(ColoresYFuentes.FUENTE_ALINEADA);
            recuadroEntrada.setFont(ColoresYFuentes.FUENTE_CUADRO_TEXTO_NORMAL);
            
            EntradaLoteIT eit = new EntradaLoteIT();
            _txtRecuadroEntrada = new UtilidadesTxt_(getCoordinador());
            _txtRecuadroEntrada.setComponente(recuadroEntrada);
            _txtRecuadroEntrada.setTamanoDeCampo(
                    eit.getCantidadPDC().getLongitudDeCaracteres(), 
                    eit.getCantidadPDC().getLongitudDeDecimales());
            _txtRecuadroEntrada.setPermitirSoloNumeros();
            
            // ASIGNAMOS LOS VALORES PARA LAS ETIQUETAS.
            etiquetaLote.setText(cl.getLote().getNombreParaMostrarLote());
            
            String tExistencia = Textos.formaetarNumeros(cl.getLote().getCantidad(), "0000.00");
            etiquetaExistencia.setText(tExistencia);
            
            
            add(etiquetaLote);
            add(Box.createRigidArea(new Dimension(10, 0)));
            add(etiquetaExistencia);
            add(Box.createRigidArea(new Dimension(10, 0)));
            add(recuadroEntrada);
            
            validate();
            
                        
        }
        
        
       
        
    }
    
    
    
    public void construirRenglon(ComparacionLotes comparacionLotes){
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaExistencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    public void cargarLotes(ComparacionLotes comparacionLotes) {
        
        JOptionPane.showMessageDialog(null, "pendiente cargar salida de lote");
        
    }
}
