/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panels;

import controlador.CoordinadorPaneles;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import modelo.logica.ComparacionLotes;
import modelo.logica.Validacion;
import modelo.vo.EntradaLoteVo;
import vista.UtilidadesIntefaz.ConfiguracionDePanel;
import vista.UtilidadesIntefaz.JPanelBase;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.ColoresYFuentes;

/**
 *
 * @author Particular
 */
@SuppressWarnings("serial")
public class PanelSalidaDeLoteCantidadADescontarDeLote extends JPanelBase {
    
    BigDecimal cantidadTotalSalida;
    List<PanelSalidaLoteContenedorDeFila> listContenedorFila = new ArrayList<>();
    
    /**
     * Creates new form PanelSalidaDeLoteCantidadADescontarDeLote
     */
    public PanelSalidaDeLoteCantidadADescontarDeLote() {
        initComponents();
        configuracionesDialogo = new ConfiguracionDePanel();
        configuracionesDialogo.setModal(true);
        configuracionesDialogo.setResizable(false);
        configuracionesDialogo.setTitle(CoordinadorPaneles.PANEL_SALIDA_LOTE_SELECCION_DE_LOTES);
        configuracionesDialogo.setLocationRelativeTo(null);
        configuracionesDialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        etiquetaExistencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiquetaSalidaRestante = new javax.swing.JLabel();

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        etiquetaExistencia.setBackground(new java.awt.Color(51, 51, 51));
        etiquetaExistencia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaExistencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaExistencia.setText("Existencia");
        etiquetaExistencia.setOpaque(true);
        etiquetaExistencia.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lote");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Salida");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modifcar salida por lote.");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Salida restante:");

        etiquetaSalidaRestante.setBackground(new java.awt.Color(51, 51, 51));
        etiquetaSalidaRestante.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaSalidaRestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSalidaRestante.setText("  200.00");
        etiquetaSalidaRestante.setOpaque(true);
        etiquetaSalidaRestante.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiquetaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaSalidaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaSalidaRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //1- REVISAMOS QUE NO HAYA NADA NEGATIVO. 
        List<Validacion> listVal =  
                getCoordinador()
                        .salidaLoteCantidadADescontarDeLoteValidaciones(
                                listContenedorFila, 
                                new BigDecimal(etiquetaSalidaRestante.getText()));
        
        boolean todoValido = true;
        for (Validacion val : listVal) {
            
            if (val.getNombreDeCampo().equals("Existencia") &&!val.isValido()) {
                JOptionPane.showMessageDialog(this, val.getMensajeDeError());
                todoValido = false;
                break;
            }else{
                todoValido = true;
            }
            
            
            if (val.getNombreDeCampo().equals("Total negativo")&&!val.isValido()) {
                int r = JOptionPane.showConfirmDialog(
                        this, val.getMensajeDeError() + "\n"
                          + "¿Quieres dejar los lotes tal como estan?", 
                        "Confirmar acción. ", 
                        JOptionPane.YES_NO_OPTION);
                
                if (JOptionPane.YES_OPTION==r) {
                    todoValido = true;
                    cantidadTotalSalida = new BigDecimal(0);
                    for (PanelSalidaLoteContenedorDeFila cF : listContenedorFila) {
                        cantidadTotalSalida = 
                                cantidadTotalSalida.add(
                                        new BigDecimal(
                                                cF.getRecuadroEntrada().getText()));
                    }
                    
                }else{
                    todoValido = false;
                    break;
                }
            }
            
        }
        
        if (todoValido) {
            List<EntradaLoteVo> listEntradaLotesModificados = new ArrayList<>();
            for (PanelSalidaLoteContenedorDeFila cF : listContenedorFila) {
                cF.consolidadExistenciaModificadaPorUsuario();
                listEntradaLotesModificados.add(cF.cl.getLote());
            }
            //COMO PASAMOS UNA REFERENCIA A LOS OBJETOS LOS DATOS SE MODIFICARON
            // EN voActualMultiple EN EL PANEL salidaDeLote
            limpiar();
            dispose();
        }
        

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    @Override
    public void initConfig() {
    }
    
    
    public void configurar() {
        panelContenedor.removeAll();
    }
    
    public void cargarLotes(List<ComparacionLotes>comparacionLotes,float cantidadSalida){
        cantidadTotalSalida = new BigDecimal(cantidadSalida);
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.X_AXIS));
        JPanel subPanel = new JPanel();
        subPanel.setLayout(new BoxLayout(subPanel, BoxLayout.Y_AXIS));
        for (ComparacionLotes cl : comparacionLotes) {
            PanelSalidaLoteContenedorDeFila f = new PanelSalidaLoteContenedorDeFila(cl);
            f.setR(()->sumarTodo());
            listContenedorFila.add(f);
            f.setCoordinador(getCoordinador());
            subPanel.add(f);
            subPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        }
        JScrollPane jScrollPane = new JScrollPane(subPanel);
        jScrollPane.setPreferredSize(new Dimension(panelContenedor.getSize()));
        panelContenedor.add(jScrollPane);
                
        panelContenedor.validate();
        this.validate();
        
        BigDecimal totalCuadros = new BigDecimal(0);
        for (PanelSalidaLoteContenedorDeFila cF : listContenedorFila) {
            BigDecimal t = new BigDecimal(cF.cl.getExistenciaPreFinal());
            totalCuadros = totalCuadros.add(t);
        }
        totalCuadros = totalCuadros.subtract(cantidadTotalSalida);
        etiquetaSalidaRestante.setText(totalCuadros.toString());
    }
    
    
    public void sumarTodo(){
        BigDecimal totalCuadros = new BigDecimal(0);
        for (PanelSalidaLoteContenedorDeFila cF : listContenedorFila) {
            totalCuadros = totalCuadros.add(cF.getCantidadAgreadaPorUsuario());
        }
        
        totalCuadros = cantidadTotalSalida.subtract(totalCuadros);
        etiquetaSalidaRestante.setText( totalCuadros.toString());
        
    }
    
    public void colorearEtiquetaSalidaRestante(){
        BigDecimal totalCuadros = new BigDecimal(etiquetaSalidaRestante.getText());
        if (totalCuadros.signum()==-1) {
            etiquetaSalidaRestante.setBackground(ColoresYFuentes.ERROR_TXT_RESALTAR_BG);
            etiquetaSalidaRestante.setForeground(ColoresYFuentes.ERROR_TXT_RESALTAR_FG);
        }else{
            etiquetaSalidaRestante.setBackground(ColoresYFuentes.TEMA_FONDO_ETIQUETAS_OSCURO);
            etiquetaSalidaRestante.setForeground(ColoresYFuentes.TEMA_TXT_FG);
        }
    }
    public void limpiar (){
        for (PanelSalidaLoteContenedorDeFila cF : listContenedorFila) {
            cF.cantidadAgreadaPorUsuario = new BigDecimal (0);
            cF.etiquetaExistencia.setText(cF.cl.getLote().getCantidad()+"");
            cF.recuadroEntrada.setText(0.0+"");
            cF.colorearEtiqueta();
        }
        etiquetaSalidaRestante.setText(cantidadTotalSalida.toString());
        colorearEtiquetaSalidaRestante();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaExistencia;
    private javax.swing.JLabel etiquetaSalidaRestante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
   
}
