/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panels;

import controlador.CoordinadorPaneles;
import java.util.HashMap;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.InfoTabla.SeccionDeMaquinaIT;
import modelo.Textos;
import modelo.logica.Validacion;
import modelo.vo.MaquinaModeloVo;
import modelo.vo.RefaccionVo;
import modelo.vo.SeccionDeMaquinaVO;
import vista.UtilidadesIntefaz.ConfiguracionDePanel;
import vista.UtilidadesIntefaz.ConfirmacionExahustiva;
import vista.UtilidadesIntefaz.JPanelBase;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesBotones_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesListas_;
import vista.UtilidadesIntefaz.utilidadesOptimizadas.UtilidadesTxt_;

/**
 *
 * @author Particular
 */
public class PanelSeccionMaquinaRelacionModeloMaquina extends JPanelBase {

    private static final long serialVersionUID = 1L;
    private UtilidadesListas_ _listaModelosMaquinaAsignados;
    private UtilidadesListas_ _listaModelosMaquinaDisponibles;
    private UtilidadesListas_ _listaRefaccionesAsignadas;
    private UtilidadesListas_ _listaRefaccionesDisponibles;
    private UtilidadesListas_ _listaSecciones;
    
    private UtilidadesTxt_ _txtNombre;
    private UtilidadesTxt_ _txtBusqueda;
    
    private SeccionDeMaquinaVO idActual;
    
//    HashMap<MaquinaModeloVo, List<RefaccionVo>> mapaDeRelaciones;
    
    
    
    /**
     * Creates new form PanelSeccionMaquinaRelacionModeloMaquina
     */
    public PanelSeccionMaquinaRelacionModeloMaquina() {
        initComponents();
//        this.mapaDeRelaciones = new HashMap<>();
        configuracionesDialogo = new ConfiguracionDePanel();
        configuracionesDialogo.setModal(true);
        configuracionesDialogo.setResizable(false);
        configuracionesDialogo.setTitle(CoordinadorPaneles.PANEL_SECCION_DE_MAQUINAS);
        configuracionesDialogo.setLocationRelativeTo(null);
        configuracionesDialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        etiquetaNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        etiquetaNombreDeLaRefaccion1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaSecciones = new javax.swing.JList<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaModelosMaquinaAsignados = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaModelosMaquinaDisponibles = new javax.swing.JList<>();
        etiquetaNombreDeLaRefaccion = new javax.swing.JLabel();
        etiquetaNombreDeLaRefaccion3 = new javax.swing.JLabel();
        etiquetaNombreDeLaRefaccion4 = new javax.swing.JLabel();
        etiquetaNombreDeLaRefaccion5 = new javax.swing.JLabel();
        etiquetaNombreDeLaRefaccion6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaRefaccionesAsignadas = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaRefaccionesDisponibles = new javax.swing.JList<>();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        txtBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_tache.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_tache.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        etiquetaNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaNombre.setText("Nombre.");

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setMaximumSize(new java.awt.Dimension(395, 2147483647));
        txtNombre.setMinimumSize(new java.awt.Dimension(395, 35));

        etiquetaNombreDeLaRefaccion1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaNombreDeLaRefaccion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_titulo_SeccionMaquina Registro y asignacion de secciones.png"))); // NOI18N
        etiquetaNombreDeLaRefaccion1.setText("Registrar/modificar seccion");

        listaSecciones.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listaSecciones.setFocusable(false);
        jScrollPane5.setViewportView(listaSecciones);

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_palomita.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        listaModelosMaquinaAsignados.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        listaModelosMaquinaAsignados.setFocusable(false);
        jScrollPane6.setViewportView(listaModelosMaquinaAsignados);

        listaModelosMaquinaDisponibles.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        listaModelosMaquinaDisponibles.setFocusable(false);
        jScrollPane7.setViewportView(listaModelosMaquinaDisponibles);

        etiquetaNombreDeLaRefaccion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaNombreDeLaRefaccion.setText("Modelos disponibles.");

        etiquetaNombreDeLaRefaccion3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaNombreDeLaRefaccion3.setText("Modelos asignados.");

        etiquetaNombreDeLaRefaccion4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        etiquetaNombreDeLaRefaccion4.setText("Asignar sección a modelo de máquina.");

        etiquetaNombreDeLaRefaccion5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaNombreDeLaRefaccion5.setText("Refacciones disponibles.");

        etiquetaNombreDeLaRefaccion6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        etiquetaNombreDeLaRefaccion6.setText("Refacciones asignadas.");

        listaRefaccionesAsignadas.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        listaRefaccionesAsignadas.setFocusable(false);
        jScrollPane8.setViewportView(listaRefaccionesAsignadas);

        listaRefaccionesDisponibles.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        listaRefaccionesDisponibles.setFocusable(false);
        jScrollPane9.setViewportView(listaRefaccionesDisponibles);

        btnLimpiar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextPane1.setText("Selecciona un modelo de máquina de la lista de \"Modelos asignados\" para relacionarlo con una o varias refacciones. ");
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jTextPane1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        txtBusqueda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBusqueda.setMaximumSize(new java.awt.Dimension(395, 2147483647));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(395, 35));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/iconos_buscar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(etiquetaNombreDeLaRefaccion5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaNombreDeLaRefaccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 132, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 291, Short.MAX_VALUE)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(etiquetaNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpiar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaNombreDeLaRefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaNombreDeLaRefaccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(etiquetaNombreDeLaRefaccion6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaNombreDeLaRefaccion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(300, 300, 300))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane6, jScrollPane7, jScrollPane8, jScrollPane9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaNombreDeLaRefaccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLimpiar)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(etiquetaNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(etiquetaNombreDeLaRefaccion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombreDeLaRefaccion)
                    .addComponent(etiquetaNombreDeLaRefaccion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombreDeLaRefaccion5)
                    .addComponent(etiquetaNombreDeLaRefaccion6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarSeccion();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (idActual==null) {
            guardarNuevaSeccion();
        }else{
            modificarSeccion();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion1;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion3;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion4;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion5;
    private javax.swing.JLabel etiquetaNombreDeLaRefaccion6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> listaModelosMaquinaAsignados;
    private javax.swing.JList<String> listaModelosMaquinaDisponibles;
    private javax.swing.JList<String> listaRefaccionesAsignadas;
    private javax.swing.JList<String> listaRefaccionesDisponibles;
    private javax.swing.JList<String> listaSecciones;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initConfig() {
           /*
        =======================================================================
            INICIO SETEO NOMBRES DE ETIQUETA
        ///////////////////////////////////////////////////////////////////////
        */
        SeccionDeMaquinaIT sdmIT = new SeccionDeMaquinaIT();
        etiquetaNombre.setText(sdmIT.getNombreSeccionPDC().getNombreParaMostrar());
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN SETEO NOMBRES DE ETIQUETA
        ========================================================================
        */
        
        /*
        =======================================================================
            INICIO SETEO UTILIDADES
        ///////////////////////////////////////////////////////////////////////
        */
        //INICIAMOS LAS UTILIDADES.
        _listaModelosMaquinaAsignados = new UtilidadesListas_(getCoordinador());
        _listaModelosMaquinaDisponibles = new UtilidadesListas_(getCoordinador());
        _listaRefaccionesAsignadas = new UtilidadesListas_(getCoordinador());
        _listaRefaccionesDisponibles = new UtilidadesListas_(getCoordinador());
        _listaSecciones = new UtilidadesListas_(getCoordinador());
        
        _txtNombre = new UtilidadesTxt_(getCoordinador());
        _txtBusqueda = new UtilidadesTxt_(getCoordinador());
        
        //SETEAMOS LOS COMPONENTES DENTRO DE LA UTILIDAD.
        
       _listaModelosMaquinaDisponibles.setComponente(listaModelosMaquinaDisponibles);
       _listaModelosMaquinaAsignados.setComponente(listaModelosMaquinaAsignados);
       _listaModelosMaquinaDisponibles.setComponenteListaAAgregar(_listaModelosMaquinaAsignados);
       
       _listaRefaccionesDisponibles.setComponente(listaRefaccionesDisponibles);
       _listaRefaccionesAsignadas.setComponente(listaRefaccionesAsignadas);
       _listaRefaccionesAsignadas.setComponenteListaAAgregar(_listaRefaccionesAsignadas);
       
       _listaSecciones.setComponente(listaSecciones);
       
       _txtNombre.setComponente(txtNombre);
       _txtBusqueda.setComponente(txtBusqueda);
              
        
        //ASIGNAMOS EL TAMAÑO DE CAMPO
        
        _txtNombre.setTamanoDeCampo(sdmIT.getNombreSeccionPDC().getLongitudDeCaracteres());
        _txtBusqueda.setTamanoDeCampo(200);
        
        //CAMPOS QUE REQUIEREN TEXTO EN MAYUSCULAS.
        _txtNombre.setPermitirSoloMayusculas();
        _txtBusqueda.setPermitirSoloMayusculas();
        
        //CAMPOS NUMÉRICOS
        
        
        //QUITAMOS LOS ESPACIOS SOBRANTES DESPUES DE DEJAR EL CAMPO.
        _txtNombre.setEspaciosEnBlanco();
        _txtBusqueda.setEspaciosEnBlanco();

        //TRAVEL POLICY
        
        _txtNombre.setNextFocusableComponent(btnGuardar);
        btnGuardar.setNextFocusableComponent(btnCancelar);
        btnCancelar.setNextFocusableComponent(btnEliminar);
        btnEliminar.setNextFocusableComponent(btnLimpiar);
        btnLimpiar.setNextFocusableComponent(_txtNombre.getThis());
        
        //ACCIONES ESPECELIALES.
            /*Cargar las secciones seleccionadas*/
        _listaSecciones.setValueChange(this::cargarDatosDeListaParaModificar);
        
        _listaModelosMaquinaDisponibles.setValueChange(()->_listaModelosMaquinaDisponibles.cambioEntreListas(false));
        _listaModelosMaquinaAsignados.setValueChange(()->_listaModelosMaquinaDisponibles.cambioEntreListas(true));
        
        _listaRefaccionesDisponibles.setValueChange(()->_listaRefaccionesAsignadas.cambioEntreListas(true));
        _listaRefaccionesAsignadas.setValueChange(() -> _listaRefaccionesAsignadas.cambioEntreListas(false));
        
            /*Carga las refacciones compatibles o las quita*/
        _listaModelosMaquinaDisponibles.addOperacionAlIntercambiarItem(this::cargarListaDeRefaccionesParaModificar, true);
        _listaModelosMaquinaDisponibles.addOperacionAlIntercambiarItem(this::cargarListaDeRefaccionesParaModificar, false);
        
            /*Filtra las refacciones*/
        _txtBusqueda.setKeyTyped(this::filtrarRefaccionesDisponibles, UtilidadesTxt_.TECLA_CUALQUIERA);
       
        
        
        
//        _listaRefaccionesDisponibles.addOperacionAlIntercambiarItem(() -> this.agregarDatosAlMapaRefacciones(), true);
//        _listaRefaccionesDisponibles.addOperacionAlIntercambiarItem(() -> this.agregarDatosAlMapaRefacciones(), false);
        
        //ACCIONES DE BOTONES
        UtilidadesBotones_.setEnterYEspacio(btnCancelar);
        UtilidadesBotones_.setEnterYEspacio(btnEliminar);
        UtilidadesBotones_.setEnterYEspacio(btnGuardar);
        UtilidadesBotones_.setEnterYEspacio(btnLimpiar);
        
        //OPERACIONES DE ACTUALIZACION
        
        opAct.add(SeccionDeMaquinaIT.NOMBRE_TABLA, this::cargarListaSecciones);
        opAct.add(SeccionDeMaquinaIT.NOMBRE_TABLA, this::cargarListaMaqModelo);
        
        /* 
        ////////////////////////////////////////////////////////////////////////
            FIN SETEO DE UTILIDADES
        ========================================================================
        */
        
    }

    @Override
    public void configurar() {

    }

    private void cancelar() {
        limpiar();
        dispose();
    }

    private void cargarListaSecciones() {
        _listaSecciones.limpiar();
        List<SeccionDeMaquinaVO> listVO = getCoordinador().seccionDeMaquinaConsultar();
        HashMap<String, Object> mapa = new HashMap<>();
        
        for (SeccionDeMaquinaVO v : listVO) {
            mapa.put(v.getNombreSeccion(), v);
        }
        
        _listaSecciones.cargarLista(mapa);

    }
    
    /**
     * Carga los datos para modificarlos de la sección que se seleccione de la
     * lista.  
     */
    @SuppressWarnings("unchecked")
    private void cargarDatosDeListaParaModificar(){
        limpiar();
        Object o = _listaSecciones.getSelectValueId();
        if (!o.equals(-1)) {
            SeccionDeMaquinaVO v = (SeccionDeMaquinaVO)o;
            _txtNombre.setText(v.getNombreSeccion());
            idActual = v;
            
            //OBTENEMOS LA LISTA DE LOS MODELOS RELACCIONADOS C
            //QUE YA ESTABAN ASGINADOS.
            List<MaquinaModeloVo> listVOQuitar = getCoordinador().maquinaModeloRelacionSeccion(idActual);
            //CARGAMOS LA LISTA DE MODELOS DE MÁQUINA. 
            cargarListaMaqModelo(listVOQuitar);

        }
    }
     
    /**
     * Esta operación carga todas los modelos de máquina.  
     */
    private void cargarListaMaqModelo() {
        cargarListaMaqModelo(null);
    }
    
    /**
     * Con esta operacion cargamos la lista de máquinas modelos para guardar una
     * nueva o para modificarla. Si se le pasa el parametro en null se cargaran
     * todas los modelos de maquina disponibles. 
     */
    private void cargarListaMaqModelo(List<MaquinaModeloVo>listMaquinaModeloAsigandos) {
        //LIMPIAMOS LA LISTA MAQUINAS MODELO DISPONIBLES. 
        _listaModelosMaquinaDisponibles.limpiar();
        
        //EN ESTA LISTA ALAMACENAREMOS TODAS LOS MODELOS DE MÁQUINA EXISTENTES. 
        List<MaquinaModeloVo> listMMVOdisponibles ;
        
        //SI NO LE PASAMOS NINGÚNA REFACCIÓN QUIERE DECIR QUE NO SE HA SELECCIONADO
        // NADA DE LA LISTA DE SECCIÓNES Y ES UNA NUEVA SEECCION
        if (listMaquinaModeloAsigandos==null) {
            //CARGAMOS TODOS LOS MODELOS DISPONIBLES. 
            listMMVOdisponibles = getCoordinador().maquinaModeloConsultar();
            //EL MAPA CON EL CARGAREMOS LOS DATOS
            HashMap<String, Object> mapa = new HashMap<>();
            //PASAMO LOS DATOS AL MAPA. 
            listMMVOdisponibles.forEach(vo->{
                mapa.put(vo.getModelo()+" "+vo.getAnio(), vo);
            });
            //CARGAMOS LA LISTA
            _listaModelosMaquinaDisponibles.cargarLista(mapa);
            
        } else {
            //LA LISTA listMaquinaModeloAsignados CONTENIA ELEMENTOS Y PORTANDO
            //QUIERE DECIR QUE ES UNA SECCIÓN QUE SE VA A MODIFICAR. 
            
            //CARGAMOS LOS MODELOS DE MAQUINA DISPONIBLES. 
            listMMVOdisponibles = getCoordinador().maquinaModeloConsultar();
            //CARGAMOS LAS MAQUINAS QUE YA HABIAN SIDO ASIGNADAS A ESTA SECCION.

            //ELIMINAMOS LOS MODELOS DE MAQUINA YA SELECCIONADOS DE LOS DISPONIBLES. 
            listMaquinaModeloAsigandos.forEach(vo->{
                if (listMMVOdisponibles.contains(vo)) {
                    listMMVOdisponibles.remove(vo);
                }
            });
            
            //LOS MAPAS PARA CARGAR LAS LISTAS
            HashMap<String, Object> mapaAsignados = new HashMap<>();
            HashMap<String, Object> mapaDisponibles = new HashMap<>();
            
            //PASAMOS LOS DATOS DE LA LISTA A LOS MAPAS
            listMMVOdisponibles.forEach(vo->{
                mapaDisponibles.put(vo.getModelo()+" "+vo.getAnio(), vo);
            });
            
            listMaquinaModeloAsigandos.forEach(vo->{
                mapaAsignados.put(vo.getModelo()+" "+vo.getAnio(), vo);
            });
            
            //CARGAMOS LAS LISTAS. 
            _listaModelosMaquinaDisponibles.cargarLista(mapaDisponibles);
            _listaModelosMaquinaAsignados.cargarLista(mapaAsignados);
            
            //CARGAMOS EL MAPA CON LAS REFACCIONES QUE SABEMOS QUE YA TIENEN
            // UNA SECCIÓN ASIGNADA. 
            
//            listMaquinaModeloAsigandos.forEach(mmvo->{
//                //CONSULTAMOS LAS REFACCIONES QUE ESTEN RELACIONADAS CON ESTA SECCION. 
//                // Y LAS CARGAMOS EN EL MAPA PARA QUE ESTEN DISPONIBLES.
//                List<RefaccionVo> listrvo = getCoordinador().refaccionRelacionSeccionMaquina(idActual);
//                mapaDeRelaciones.put(mmvo, listrvo);
//            });
        }
    }    
    
    /**
     *Carga en la lista de refacciones disponibles las refacciones que son
     * compatibles con el modelo y si ya hay algúna relación con la sección  
     * (modificar una seccion) carga las refacciones ya seleccionadas. 
     *
     */
    private void cargarListaRefacciones(){
        if (idActual== null) {
            cargarListaDeRefaccionesParaGuardarNuevo();
        }else{
            cargarListaDeRefaccionesParaModificar();
        }
    }
    
    private void eliminarSeccion() {
        Object a = _listaSecciones.getSelectValueId();
        if (!a.equals(-1)) {
            SeccionDeMaquinaVO seccionDeMaquinaVO = (SeccionDeMaquinaVO)a;
            
            String m1 = "¿Estas segúro que quieres eliminar esta sección?";
            String m2 = "¿Estas muy segúro que quieres eliminar esta sección? Esta acción no se puede deshacer y perjudicara "
                    + " los registros que tienen relación con esta sección \n"
                    + " independientemente del modelo o refacción.¿Aun así quieres hacerlo?";
            int r = ConfirmacionExahustiva.confirmarEliminacionPeligrosa(m1, m2);
            if (r==ConfirmacionExahustiva.SI_ELIMINAR) {
                if (getCoordinador().seccionDeMaquinaEliminar(seccionDeMaquinaVO)) {
                    getCoordinador().actualizarTodoLoVisible();
                    JOptionPane.showMessageDialog(this, "Se eliminó la sección.");
                }else{
                    JOptionPane.showMessageDialog(this, "Álgo paso y no se pudo eliminar la sección.");
                }
            }
        }
    }

    /**
     * Guarda las nuevas relaciones entre las secciones y las refacciones.  
     */
    private void guardarNuevaSeccion(){
        SeccionDeMaquinaIT sdmit = new SeccionDeMaquinaIT();

        //OBTENEMOS LA NUEVA SECCIÓN.
        SeccionDeMaquinaVO sdmvo = new SeccionDeMaquinaVO();
        sdmvo.setNombreSeccion(_txtNombre.getText());
        
        //VALIDAMOS QUE NO ESTE REPETIDA. 
        List<Validacion> listVal = getCoordinador().seccionDeMaquinaValidar(sdmvo);
        
        boolean todoValido = true;
        for (Validacion val : listVal) {
            if (val.getNombreDeCampo().equals(sdmit.getNombreSeccionPDC().getNombre())) {
                if (val.isValido()) {
                    _txtNombre.setErrorQuitar();
                }else{
                    _txtNombre.setError(val.getMensajeDeError());
                    todoValido = false;
                }
            }
        }
        
        if (todoValido) {
        //LA SECCION NO EXISTE ENTONCES LA GUARDAMOS Y OBTENEMOS SU ID.
            if (getCoordinador().seccionDeMaquinaGuardar(sdmvo)) {
                todoValido = true;
                //CARGAMOS EL ID DE LA REFACCION GENERADO.
                sdmvo.setId(getCoordinador().seccionDeMaquinaUltimoId());
                if (sdmvo.getId()==-1) {
                    todoValido = false;
                    JOptionPane.showMessageDialog(this, "Algo paso y no se pudieron guardar"
                            + " las refacciones que se relacionaron. "
                            + "\nIntentalo recargando esta ventana.");
                }
            }else{
                todoValido = false;
            }
        }
        
        
        //LA LISTA QUE CONTENDRA LAS REFACCIONES COMPATIBLES. 
        
//        if (todoValido) {
//            //SI LA SECCIÓN SE GUARDO ENTONCES PROCEDEMOS A RELACIONAR EL MAPA
//            // CON LA REFACCIÓN. PARA ESTO SOLO NECESITAMOS LA REFACCIÓN
//            // POR QUE YA TENEMOS FILTRADO QUE SI ES COMPATIBLE CON EL MODELO
//            // DE LA MÁQUINA Y APARTE YA SABEMOS QUE EXISTE LA RELACIÓN.
//            
//            //DECARGAMOS TODAS LAS REFACCIONES EN UNA LISTA. 
//            // REVISANDO QUE NO ESTEN REPEDITAS. 
////            mapaDeRelaciones.forEach((MaquinaModeloVo mmvo, List<RefaccionVo> listRVO) -> {
////                for (RefaccionVo rvo : listRVO) {
////                   RelacionSeccionMaqRefaccionVO rsmrvo = new RelacionSeccionMaqRefaccionVO();
////                   rsmrvo.setIdRefaccion(rvo.getId());
////                   rsmrvo.setIdSeccionMaquina(sdmvo.getId());
////                   listRelacion.add(rsmrvo);
////                }
////            });
//            
//            if (listRelacion.isEmpty()) {
//                JOptionPane.showMessageDialog(this, 
//                        "<html>No seleccionaste ningúna refacción para \n"
//                        + " relacionarla con esta sección. Solo se guardo la sección."
//                                + "<html>");
//                todoValido = false;
//            }
//        }    
         
//        if (todoValido) {
//            //GUARDAMOS LA RELACION ENTRE LA SECCIÓN Y LA REFACCIÓN.
//            if (getCoordinador().seccionDeMaquinaRelacionRefaccionGuardar(listRelacion)) {
//                getCoordinador().actualizarTodoLoVisible();
//                JOptionPane.showMessageDialog(this, "Se guardo la sección \""+sdmvo.getNombreSeccion()+"\" "
//                        + "correctamente.");
//            }else{
//                JOptionPane.showMessageDialog(this, "No se pudo guardar la relación \n"
//                        + "entre las refacciones y la sección, pero si se guardo la sección.\n"
//                        + " Intenta modificar la sección de nuevo para agregar las refacciones asignadas.");
//            }
//        }
    }
    
    private void modificarSeccion(){
        //PARA MODIFICAR LA REFACCIONES UTILIZAMOS UN PROCEMIENTO SIMILIAR AL
        // DEL GUARDADO. SOLO QUE PRIMERO OCUPAMOS OBTENER TODAS LAS REFACCIONES
        // QUE ESTABAN ASIGNADAS A LA SECCION PERO AHORA SI QUE COINCIDAN CON LOS MODELOS
        // QUE TANBIEN ESTAN ASIGNADOS. LO BUENO ES QUE YA TENEMOS ESO. 
        
        
    }
    
    @Override
    public void limpiar(){
//        mapaDeRelaciones.clear();
        idActual = null;
        cargarListaMaqModelo();
    }

    private void cargarListaDeRefaccionesParaModificar() {
        //SELECCIONAMOS LA LISTA DE REFACCIONES QUE ESTAN ASIGNADAS Y LAS
        //UTILIZAMOS PARA FILTRAR LAS REFACCIONES QUE SERAN COMPATIBLES CON
        // ESTA SECCIÓN.
               
        
        // OBTENEMOS LOS MODELOS SELECCIONADOS. 
        @SuppressWarnings("unchecked")
        List<MaquinaModeloVo> listMMVOAsignados =
                (List<MaquinaModeloVo>)(List<?>) _listaModelosMaquinaAsignados.getItems_ObjectsRelacionados();
        if (!listMMVOAsignados.isEmpty()) {
             //OBTENEMOS LAS REFACCIONES COMPATIBLES. 
            List<RefaccionVo> listRefaccionesCompatiblesConModelo = 
                getCoordinador().refaccionConsultarCompatiblesConMaquinaModelo(listMMVOAsignados);
            cargarRefaccioneEnListaDisponibles(listRefaccionesCompatiblesConModelo);
        }else{
            _listaRefaccionesDisponibles.limpiar();
        }
    }
    
    /**
     * Carga las refacciones en la lista de refacciones disponibles con el formato
     * que ya se definio. 
     */
    private void cargarRefaccioneEnListaDisponibles(List<RefaccionVo> listRVO){
        
        //CARGAMOS LA LISTA DE DISPONIBLES.
        _listaRefaccionesDisponibles.limpiar();
        HashMap<String, Object> mapaDisponibles = new HashMap<>();

        listRVO.forEach(
                rvo->{

                    String a  = Textos.formatearEspacios(12, rvo.getCodigoProveedor(), "|");
                    String b  = Textos.formatearEspacios(25, rvo.getNombre(), "|");
                    String c  = Textos.formatearEspacios(25, rvo.getCodigoInterno(), "|");

                    mapaDisponibles.put(a+b+c, rvo);

                });

        _listaRefaccionesDisponibles.cargarLista(mapaDisponibles);
    }

    private void cargarListaDeRefaccionesParaGuardarNuevo() {
//        // SOLO CARGAMOS LAS REFACCIONES PARA ASIGNARLAS A LA MÁQUINA MODELO.
//        Object a = _listaModelosMaquinaAsignados.getSelectValueId();
//        if (!a.equals(-1)) {
//            MaquinaModeloVo mmvo = (MaquinaModeloVo)a;
//
//            //CARGAMOS LAS REFACCIONES COMPATIBLES. 
//            List<RefaccionVo> listRefacccionesCompatibles = 
//                    getCoordinador().refaccionConsultarCompatiblesConMaquinaModelo(mmvo);
//            JOptionPane.showMessageDialog(null, "Estamos en guardar nuevo"+listRefacccionesCompatibles.toString());
//
//            HashMap<String, Object> mapaDisponibles = new HashMap<>();
//            listRefacccionesCompatibles.forEach(vo->{
//                
//                mapaDisponibles.put(vo.getNombre(), vo);
//            });
//
//            _listaRefaccionesDisponibles.cargarLista(mapaDisponibles);
//            
//        }
        
        
    }
    
    
    /**
     * Agrega los datos al mapa para ordenar la relacion entre el modelo de máquina
     * y la refafacción. 
     */
    private void agregarDatosAlMapaRefacciones() {
//        //OBTENEMOS EL MODELO DE MÁQUINA SELECCIONADO. 
//        MaquinaModeloVo mmVOSeleccionado = 
//                (MaquinaModeloVo)_listaModelosMaquinaAsignados.getSelectValueId();
//        
//        //OBTENEMOS TODAS LAS REFACCIONES QUE SE LE ASIGNARON.
//        @SuppressWarnings("unchecked")
//        List<RefaccionVo> listRefaccionesSeleccionadas =
//                (List<RefaccionVo>)(List<?>)_listaRefaccionesAsignadas;
//
//        //CARGAMOS EL MAPA. 
//        mapaDeRelaciones.put(mmVOSeleccionado, listRefaccionesSeleccionadas);  
    }
    
    /**
     * Filtra las refacciones tomando en cuenta la lista de maquinas modelos 
     * asignadas. 
     */
    private void filtrarRefaccionesDisponibles() {
        if (!_txtBusqueda.isEmpty()) {
            @SuppressWarnings("unchecked")
            List<MaquinaModeloVo> listMMVo = 
                    (List<MaquinaModeloVo>)(List<?>)_listaModelosMaquinaAsignados.getItems_ObjectsRelacionados();
            
            List<RefaccionVo> listRVO = 
                    getCoordinador().refaccionConsultarCompatiblesConMaquinaModelo(
                            listMMVo, _txtBusqueda.getText());
            
            cargarRefaccioneEnListaDisponibles(listRVO);
        }else{
//            this.cargarListaRefacciones();
        }
    }

    
       
    


}

